packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  # Core
  react: ^18.3.1
  react-dom: ^18.3.1
  typescript: ^5.9.2

  # State Management
  zustand: ^4.5.5
  '@tanstack/react-query': ^5.56.0
  '@tanstack/query-async-storage-persister': ^5.56.0
  '@tanstack/react-query-persist-client': ^5.56.0

  # Backend
  '@supabase/supabase-js': ^2.45.0

  # Utilities
  date-fns: ^3.6.0
  date-fns-tz: ^3.2.0
  zod: ^4.1.12

  # Forms
  react-hook-form: ^7.65.0

  # React Native Core (for mobile only) - SDK 52
  react-native: 0.76.9

  # React Native Navigation (for mobile only)
  '@react-navigation/native': ^7.0.14
  '@react-navigation/native-stack': ^7.2.0
  '@react-navigation/bottom-tabs': ^7.2.0

  # React Native UI (for mobile only) - SDK 52 compatible
  react-native-gesture-handler: ~2.20.2
  react-native-reanimated: ~3.16.1
  react-native-safe-area-context: 4.12.0
  react-native-screens: ~4.4.0
  react-native-svg: 15.8.0

  # Expo SDK 52 packages (for mobile only)
  expo: ~52.0.0
  expo-application: ~6.0.0
  expo-device: ~7.0.0
  expo-file-system: ~18.0.0
  expo-image: ~2.0.0
  expo-image-picker: ~16.0.0
  expo-media-library: ~17.0.0
  expo-notifications: ~0.29.0
  expo-sharing: ~13.0.0
  expo-status-bar: ~2.0.0

  # Storage
  '@react-native-async-storage/async-storage': 1.23.1

  # Icons
  lucide-react-native: ^0.469.0

  # Other
  react-native-view-shot: ~4.0.0
  react-native-worklets-core: ~1.4.0
