/**
 * Report Parser Adapter for Mobile
 *
 * Re-exports from @mandaact/shared with mobile-specific interface adaptation
 * Includes i18n support for metric labels
 */

import {
  parseWeeklyReport as sharedParseWeeklyReport,
  parseDiagnosisReport as sharedParseDiagnosisReport,
  ReportSummary as SharedReportSummary,
  ReportErrorReason,
} from '@mandaact/shared'

// Re-export ReportErrorReason for use in components
export type { ReportErrorReason } from '@mandaact/shared'

/**
 * Mapping of Korean metric labels to i18n keys
 * Used to translate metric labels from Korean (generated by AI) to user's language
 */
const METRIC_LABEL_MAP: Record<string, string> = {
  // Weekly Report metrics
  '실천일수': 'reports.metrics.practiceDays',
  '총 실천횟수': 'reports.metrics.totalChecks',
  '전주대비 실천횟수': 'reports.metrics.vsLastWeek',
  '주간 목표': 'reports.metrics.weeklyGoal',
  '일평균 실천': 'reports.metrics.dailyAverage',
  '최고 실천일': 'reports.metrics.bestDay',
  // Goal Diagnosis metrics (both with and without spaces for AI variations)
  '완성도': 'reports.metrics.completeness',
  '표현명확도': 'reports.metrics.expressionClarity',
  '표현 명확도': 'reports.metrics.expressionClarity',
  '측정가능성': 'reports.metrics.measurability',
  '측정 가능성': 'reports.metrics.measurability',
  '일관성': 'reports.metrics.consistency',
  '실천 설계': 'reports.metrics.actionClarity',
  '실천설계': 'reports.metrics.actionClarity',
}

/**
 * Get i18n key for a metric label
 * Returns the original label if no translation key is found
 */
export function getMetricLabelKey(label: string): string {
  return METRIC_LABEL_MAP[label] || label
}

/**
 * Mobile-specific ReportSummary interface
 * Includes structured arrays instead of markdown content
 */
export interface ReportSummary {
  headline: string
  metrics: Array<{
    label: string
    value: string
  }>
  strengths: string[]
  improvements: {
    problem?: string
    insight?: string
    items?: Array<{
      area: string
      issue: string
      solution: string
    }>
  }
  actionPlan: string[]
  errorReason?: ReportErrorReason
}

/**
 * Convert shared ReportSummary (with markdown detailContent) to mobile format
 */
function adaptToMobileFormat(shared: SharedReportSummary): ReportSummary {
  const mobile: ReportSummary = {
    headline: shared.headline,
    metrics: shared.metrics.map(m => ({ label: m.label, value: m.value })),
    strengths: [],
    improvements: {},
    actionPlan: [],
    errorReason: shared.errorReason,
  }

  // Parse markdown detailContent into structured arrays
  if (shared.detailContent) {
    const lines = shared.detailContent.split('\n')
    let currentSection = ''

    for (const line of lines) {
      const trimmed = line.trim()

      if (trimmed.startsWith('## ')) {
        currentSection = trimmed.replace('## ', '').trim().toLowerCase()
        continue
      }

      if (trimmed.startsWith('• ') || trimmed.startsWith('- ')) {
        const content = trimmed.replace(/^[•-]\s*/, '')

        if (currentSection.includes('강점') || currentSection.includes('strength')) {
          mobile.strengths.push(content)
        } else if (currentSection.includes('개선') || currentSection.includes('improvement')) {
          if (!mobile.improvements.problem) {
            mobile.improvements.problem = content
          } else if (!mobile.improvements.insight) {
            mobile.improvements.insight = content
          }
        } else if (currentSection.includes('제안') || currentSection.includes('action')) {
          mobile.actionPlan.push(content)
        }
      }
    }
  }

  return mobile
}

/**
 * Parse weekly practice report
 * Uses shared implementation and adapts to mobile format
 */
export function parseWeeklyReport(content: string): ReportSummary {
  try {
    const shared = sharedParseWeeklyReport(content)
    return adaptToMobileFormat(shared)
  } catch (error) {
    console.error('Error parsing weekly report:', error)
    return {
      headline: '',
      metrics: [],
      strengths: [],
      improvements: {},
      actionPlan: [],
      errorReason: 'parseError',
    }
  }
}

/**
 * Parse diagnosis report
 * Uses shared implementation and adapts to mobile format
 */
export function parseDiagnosisReport(content: string): ReportSummary {
  try {
    const shared = sharedParseDiagnosisReport(content)
    return adaptToMobileFormat(shared)
  } catch (error) {
    console.error('Error parsing diagnosis report:', error)
    return {
      headline: '',
      metrics: [],
      strengths: [],
      improvements: {},
      actionPlan: [],
      errorReason: 'parseError',
    }
  }
}

